zuul:
  ignoredServices: '*'
  routes:
    auth:
      path: /auth/**
      serviceId: auth
      sensitiveHeaders:
    demo:
      path: /taskmgr/**
      serviceId: taskmgr
      sensitiveHeaders:
  prefix: /api
server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
endpoints:
  routes:
    sensitive: false
  health:
    sensitive: false
  metrics:
    enabled: true
  logfile:
    sensitive: false
    enabled: true
management:
  security:
    enabled: false
