spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/peng.wong/service-configurations.git
          username: peng.wong
          password: Wp770521
# While in development mode, you can configure the config server to pick up configuration files from
# the file system

#           uri: file://Users/anilallewar/Documents/Anil Allewar/Trainings/Code Samples/Enterprise Java/Micro Services/sample-config

# Defines the port where the config server is running so that rest of the services can pick up
# their external configurations
server:
  port: 8888
logging:
  level:
    org.springframework:
      cloud: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  profiles: docker
eureka:
  instance:
    hostname: configserver
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
